### ISSUE TITLE
Workshop spawner provisioning fails when CRW is not provisioned with it

### ISSUE THREAD

**Issue by akochnev** [jharmison-redhat/openshift-devsecops#38] opened 2020-04-30 00:38 UTC
I had deploy_crw: no in my configuration, and as a result (because the workshop-spawner depends on keycloak) workshop_spawner was failing to complete as well (waiting to the crw keykloak to come up)

**Comment by andykrohg** [comment] 2020-04-30 02:43
This is by design at the moment. We *could* parameterize the workshop-spawner component to opt for a deployment paradigm other than ```external-keycloak``` when ```deploy_crw=no```, but I struggle to see the value since the workshop-dashboard instances produced by the spawner use an image that's custom built for this workshop.

**Comment by andykrohg** [comment] 2020-04-30 02:55
Well I should say it's potentially of value to support a deployment without CRW (in case you want to skip the relevant lab(s)), but we should probably discuss whether we should make that a priority

**Comment by akochnev** [comment] 2020-04-30 20:34
@andykrohg - fair enough. All I'm saying is that there currently is an option to not install CRW, which makes a seemingly unrelated part of the workshop (workshop spawner) to fail. If these area always intended to be installed together, then it shouldn't be possible to install one and not the other.

**Comment by jharmison-redhat** [comment] 2020-07-27 15:08
Fixed in #55

**Closed as completed by jharmison-redhat** 2020-07-27 15:08 UTC
